apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-db-pv
  namespace: wpproject
  labels:
    app: wpweb     # has to match .spec.template.metadata.labels
    type: webapp
    project: wpproject-examples
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pgdbvol"
---
# Allow pvc for mysql storages mount
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-db-pvc
  namespace: wpproject
  labels:
    app: wpweb     # has to match .spec.template.metadata.labels
    type: webapp
    project: wpproject-examples
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi