apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webx
  labels:
    app: webx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: webx
  template:
    metadata:
      labels:
        app: webx
    spec:
      containers:
      - name: webx
        image: nginx:latest
        ports:
        - name: web
          containerPort:  80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: webx
spec:
  selector:
    app: webx
  type: NodePort
  ports:
  - name: webx
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31454