apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: default
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: prateekkumawat/flaskapp:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 700Mi
        ports:
        - containerPort:  80
      imagePullSecrets:
        - name: flasksecret
