apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  namespace: default
spec:
  selector:
    app: flaskapp
  type: NodePort
  ports:
  - name: flaskapp
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31500