apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
  labels:
    app: datastore     # has to match .spec.template.metadata.labels
    type: database
    project: learning-db-examples
  namespace: datastore
type: Opaque
data:
   mysqluser: prateek
   mysqlpass: passhash