apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  namespace: datastore
spec:
  selector:
    app: datastore     # has to match .spec.template.metadata.labels
    type: database
    project: learning-db-examples
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mysql-db-service
    protocol: TCP
    port: 3306
    targetPort: 3306
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 31306