apiVersion: v1
kind: Secret
metadata:
  name: wp-secrets
  namespace: datastore
  labels:
    app: datastore     # has to match .spec.template.metadata.labels
    type: database
    project: learning-db-examples
type: Opaque
data:
  wpuser: cHJhdGVlaw==     #prateek
  wppass: cmVkaGF0         # redhat
  