apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: datastore
  labels:
    app: datastore     # has to match .spec.template.metadata.labels
    type: database
    project: learning-db-examples
spec:
  selector:
    matchLabels:
      app: datastore     # has to match .spec.template.metadata.labels
      type: database
      project: learning-db-examples
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: datastore     # has to match .spec.template.metadata.labels
        type: database
        project: learning-db-examples
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: wordpress
        image: wordpress:latest
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        env:
          - name: WORDPRESS_DB_HOST
            value: mysql-db-0.datastore.svc.cluster.local
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: wppass
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wp-secret
                key: wpuser   
          - name: WORDPRESS_DB_NAME
            value: wordpress   
        ports:
        - containerPort:  80
          name: wp
        volumeMounts:
        - name: webmount
          mountPath: /var/www/html/
      volumes:
      - name: webmount
        persistentVolumeClaim:
          claimName: wp-pvc