apiVersion: batch/v1
kind: Job
metadata:
  name: jobscript
spec:
  template:
    metadata:
      name: jobscript
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4

  ### Task Perform ****
  ## Create a mysql pod and schedule daily backup on using cron *******