apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
  labels:
    app: web
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/pod2_data     # nfs server share directory
    server: 172.31.7.25  # nfs-server ip

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
  labels:
    app: web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: "web"
  namespace: default
  labels:
    app: "web"
spec:
  containers:
  - name: web
    image: "nginx:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: datavol
      mountPath: /opt
  volumes:
    - name: datavol
      persistentVolumeClaim:
        claimName: wordpress-storage