apiVersion: v1
kind: PersistentVolume
metadata:
  name: wpdbvol
  namespace: wpproject
  labels:
    app: wpweb     # has to match .spec.template.metadata.labels
    type: webapp
    project: wpproject-examples
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/wpdbvol"
---
# Allow pvc for mysql storages mount
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
  namespace: wpproject
  labels:
    app: wpweb     # has to match .spec.template.metadata.labels
    type: webapp
    project: wpproject-examples
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi